spring:
  profiles:
    active: local
  messages:
    basename: i18n/exception
    encoding: UTF-8
  social:
    kakao:
      client_id: 359532de267ffbac4b4a40789204351d
      redirect: /social/login/kakao
      url:
        login: https://kauth.kakao.com/oauth/authorize
        token: https://kauth.kakao.com/oauth/token
        profile: https://kapi.kakao.com/v2/user/me
  jwt:
    secret: govlepel@$&
#spring:
#  datasource:
#    url: jdbc:h2:tcp://localhost/~/test
#    driver-class-name: org.h2.Driver
#    username: sa
#  jpa:
#    database-platform: org.hibernate.dialect.H2Dialect
#    properties.hibernate.hbm2ddl.auto: update
#    showSql: true